name: the_movie_box
description: "a simple movie app"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.4.1
  flutter_dotenv: ^5.2.1
  connectivity_plus: ^6.1.0
  dio_smart_retry: ^6.0.0
  dio_cache_interceptor_hive_store: ^3.2.2
  dio_cache_interceptor: ^3.5.0
  fluttertoast: ^8.2.8
  get_storage: ^2.1.1
  equatable: ^2.0.5
  get_it: ^8.0.0
  graphql_flutter: ^5.2.0-beta.7
  scrollable_tab_view: ^1.0.9
  intl: ^0.19.0
  url_launcher: ^6.3.1
  firebase_core: ^3.6.0
  firebase_performance: ^0.10.0+8
  firebase_remote_config: ^5.1.3
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  provider: ^6.1.2
  path_provider: ^2.1.4
  app_links: ^6.3.2
  go_router: ^14.3.0
  share_plus: ^10.1.0
  flutter_translate: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/png/
